Repository CBNU-SUPER-NOVA/PC_Supporter, pull requests merged in 2024-10, with the labels that each got.

#28 Feat: add prompt setting
  gpt_api/api.py
  gui/componets/PromptInputPanel.py
Labels: feature

#41 Feat: add Gemini API
  gpt_api/api.py
  gui/componets/PromptInputPanel.py
  gui/side_panel.py
Labels: feature

#54 Create How to Get API Key.md
  How to Get API Key.md
Labels: documentation

#61 Feat/api auth
  gpt_api/api.py
  gui/componets/PromptInputPanel.py
  gui/componets/side/Setting.py
  utils/code_executor.py
Labels: feature

#65 Refact: prompt setting change msg
  gui/SidePanel.py
Labels: refactor

#70 Refact/load api key
  gpt_api/api.py
  requirements.txt
Labels: refactor

#71 refact: API Key load과정 중 db와 충돌나던 문제 해결
  gpt_api/api.py
Labels: refactor

#78 [Docs] : Modify Information
  gui/components/side/Informaiton.py
Labels: documentation

#79 GUI : Fonts , MinSize , Text bug
  gui/AiPanel.py
  gui/CodePanel.py
  gui/components/__init__.py
  gui/components/chat/AIChatBox.py
  gui/components/chat/MyChatBox.py
  gui/components/chat/PromptInputPanel.py
  gui/components/common/CodeBox.py
  gui/components/common/Font.py
  gui/components/common/RoundedPanel.py
  main.py
Labels: bug, feature

#81 Del: delete dummy code
  gpt_api/api.py
  gui/components/chat/PromptInputPanel.py
  gui/components/side/PromptSetting.py
  utils/code_executor.py
Labels: invalid
